FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./frontend/package*.json /app
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port for development server
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]