version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  laravel:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: laravel
    restart: unless-stopped
    # ports:
    #   - "9000:9000"
    volumes:
      - ./backend:/var/www
    networks:
      - backend

  sveltekit:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: sveltekit
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    networks:
      - frontend

  db:
    image: postgres:13
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local