version: '3.8'

services:

  laravel:
    build:
      context: ./backend
    image: laravel
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/vendor:/var/www/vendor #Laravel specific
    networks:
      - app-network
    ports:
      - "9000:9000"

  sveltekit:
    build:
      context: ./frontend
    image: sveltekit
    container_name: sveltekit
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    ports:
      - "5173:5173"

  db:
    image: postgres:13
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
