FROM php:8.3-fpm-alpine

# Install necessary libraries for GD and PostgreSQL
RUN apk --update --no-cache add \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    postgresql-dev \
    bash \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_pgsql pgsql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# Set the working directory
WORKDIR /var/www

# Copy application code
COPY ./backend /var/www
COPY ./backend/www.conf /usr/local/etc/php-fpm.d/ue.conf
# Set environment variable to allow Composer to run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

# Install Composer dependencies
RUN composer install

# Expose port for development
EXPOSE 9000

# Start PHP-FPM
CMD ["php-fpm"]